language: node_js
sudo: false

node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"

branches:
    only:
      - master

install:
    - npm install

before_script:
  - npm install -g babel

script:
  - npm test
