language: node_js
sudo: false

node_js:
  - "4.1"
  - "4.0"

branches:
    only:
      - master

install:
    - npm install

before_script:
    - npm install -g grunt grunt-cli babel-cli

script:
    - npm test
